version: "3.7"
services:
  web-server:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "./html/:/var/www/html/"
    ports:
      - "8080:80"
      
  mysql-server:
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
      
   phpmyadmin:
    image: phpmyadmin / phpmyadmin: 5.0.1
    reiniciar: siempre
    entorno:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: secreto
    puertos:
      - "5000: 80"
volúmenes:
  mysql-data:
